# -*- coding: utf-8 -*-
"""MLT_Kasus2_MUHAMMAD IQBAL SAPUTRA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Ohp9ae6HgU1ZiPV3rBnd9qWub0UlOmW

# Proyek Akhir Machine Learning Terapan: Sistem Rekomendasi Buku
Oleh: Muhammad iqbal Saputra

## 1. Persiapan Workspace dan Import Library
Tahap ini digunakan untuk mengimpor seluruh pustaka yang dibutuhkan serta mengunduh dataset langsung dari Kaggle menggunakan API.
"""

# Import library standar
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Import library untuk Content-Based Filtering
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Import library untuk Collaborative Filtering
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Mengunggah file kaggle.json
from google.colab import files
print("Silakan unggah file kaggle.json Anda:")
uploaded = files.upload()

# Mengunduh dataset menggunakan Kaggle API
# Pastikan Anda sudah mengunggah file kaggle.json ke sesi Colab
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!kaggle datasets download -d arashnic/book-recommendation-dataset
!unzip -q book-recommendation-dataset.zip -d dataset

"""## 2. Data Understanding
Memuat data dari berkas CSV ke dalam Pandas DataFrame untuk melihat struktur data, jumlah baris, dan fitur yang tersedia. Dataset terdiri dari data Buku, Rating, dan Pengguna.
"""

# Memuat data
books = pd.read_csv('dataset/Books.csv', low_memory=False)
ratings = pd.read_csv('dataset/Ratings.csv')
users = pd.read_csv('dataset/Users.csv')

print(f"Jumlah baris data Buku: {len(books)}")
print(f"Jumlah baris data Rating: {len(ratings)}")
print(f"Jumlah baris data Pengguna: {len(users)}")

print("\nStruktur data Buku: \n")
display(books.head(3))
print("\nStruktur data Rating: \n")
display(ratings.head(3))
print("\nStruktur data Pengguna: \n")
display(users.head(3))

"""## 3. Exploratory Data Analysis (EDA)
Melihat distribusi rating yang diberikan oleh pengguna untuk memahami tendensi penilaian secara umum.
"""

plt.figure(figsize=(10, 5))

sns.countplot(x='Book-Rating', data=ratings, hue='Book-Rating', palette='viridis', legend=False)

plt.title('Distribusi Rating Buku')
plt.xlabel('Rating (0-10)')
plt.ylabel('Jumlah')
plt.show()

"""## 4. Data Preparation
Tahapan ini meliputi pembersihan data, penggabungan dataset, penanganan _missing values_, serta _subsetting_ agar komputasi tidak mengalami _Out of Memory_ (RAM _crash_) saat melatih model.
"""

# Menghapus kolom URL gambar yang tidak relevan untuk pemodelan
books_clean = books.drop(columns=['Image-URL-S', 'Image-URL-M', 'Image-URL-L'])

# Hanya mengambil rating eksplisit (Rating > 0)
ratings_explicit = ratings[ratings['Book-Rating'] > 0]

# Menggabungkan data rating dan buku berdasarkan ISBN
df_merged = ratings_explicit.merge(books_clean, on='ISBN', how='inner')

# Pengecekan jumlah baris dan kolom
print("Bentuk data books:", books.shape)
print("Bentuk data ratings:", ratings.shape)
print("Bentuk data users:", users.shape)

# Pengecekan Missing Value tiap dataset
print("\nMissing Value Books:\n", books.isnull().sum())
print("\nMissing Value Ratings:\n", ratings.isnull().sum())
print("\nMissing Value Users:\n", users.isnull().sum())

# Pengecekan Duplikat tiap dataset
print("\nDuplikat Books:", books.duplicated().sum())
print("Duplikat Ratings:", ratings.duplicated().sum())
print("Duplikat Users:", users.duplicated().sum())

# lakukan dropna
df_merged = df_merged.dropna()

# Mengambil sampel 10.000 data secara acak untuk efisiensi memori (opsional namun sangat disarankan)
df = df_merged.sample(n=10000, random_state=42).reset_index(drop=True)

print(f"Jumlah data setelah proses preparation: {len(df)}")
display(df.head(3))

"""## 5. Model Development: Content-Based Filtering
Membangun sistem rekomendasi berdasarkan kemiripan nama Penulis (Author). Buku yang ditulis oleh penulis yang sama atau memiliki gaya penulisan serupa akan direkomendasikan. Algoritma yang digunakan adalah TF-IDF Vectorizer dan Cosine Similarity.
"""

# Mempersiapkan dataframe khusus untuk Content-Based
preparation = df.drop_duplicates('ISBN').reset_index(drop=True)

# Inisialisasi TfidfVectorizer
tfidf = TfidfVectorizer()

# Melakukan perhitungan idf pada data Book-Author
tfidf_matrix = tfidf.fit_transform(preparation['Book-Author'])

# Menghitung Cosine Similarity pada matriks tf-idf
cosine_sim = cosine_similarity(tfidf_matrix)

# Membuat dataframe similarity
cosine_sim_df = pd.DataFrame(cosine_sim, index=preparation['Book-Title'], columns=preparation['Book-Title'])

# Fungsi untuk mendapatkan rekomendasi Top-N
def book_recommendations(nama_buku, similarity_data=cosine_sim_df, items=preparation[['Book-Title', 'Book-Author', 'Publisher']], k=5):
    # Mengambil data dengan similarity tertinggi dari index
    index = similarity_data.loc[:,nama_buku].to_numpy().argpartition(range(-1, -k-1, -1))

    # Mengambil data dengan similarity terbesar
    closest = similarity_data.columns[index[-1:-(k+2):-1]]

    # Drop nama_buku agar tidak merekomendasikan buku yang sama
    closest = closest.drop(nama_buku, errors='ignore')

    return pd.DataFrame(closest).merge(items).drop_duplicates().head(k)

# Menguji Model Content-Based
sample_book = preparation['Book-Title'].iloc[10]
print(f"Rekomendasi untuk buku: {sample_book} (Penulis: {preparation[preparation['Book-Title'] == sample_book]['Book-Author'].values[0]})")
display(book_recommendations(sample_book))

"""## 6. Model Development: Collaborative Filtering
Merekomendasikan buku berdasarkan pola histori interaksi *user-item*. Menggunakan *Deep Learning* dengan *Embedding Layer* untuk mengkalkulasi kecocokan antarpengguna.
"""

# Menyalin data
df_collab = df.copy()

# Encoding User-ID
user_ids = df_collab['User-ID'].unique().tolist()
user_to_user_encoded = {x: i for i, x in enumerate(user_ids)}
user_encoded_to_user = {i: x for i, x in enumerate(user_ids)}
df_collab['user'] = df_collab['User-ID'].map(user_to_user_encoded)

# Encoding ISBN
book_ids = df_collab['ISBN'].unique().tolist()
book_to_book_encoded = {x: i for i, x in enumerate(book_ids)}
book_encoded_to_book = {i: x for i, x in enumerate(book_ids)}
df_collab['book'] = df_collab['ISBN'].map(book_to_book_encoded)

# Jumlah user dan book
num_users = len(user_to_user_encoded)
num_books = len(book_to_book_encoded)

# Normalisasi Rating
min_rating = min(df_collab['Book-Rating'])
max_rating = max(df_collab['Book-Rating'])
df_collab['rating_norm'] = df_collab['Book-Rating'].apply(lambda x: (x - min_rating) / (max_rating - min_rating))

# Train-Test Split (80:20)
x = df_collab[['user', 'book']].values
y = df_collab['rating_norm'].values

train_indices = int(0.8 * df_collab.shape[0])
x_train, x_val, y_train, y_val = (x[:train_indices], x[train_indices:], y[:train_indices], y[train_indices:])

# Arsitektur Model RecommenderNet
class RecommenderNet(tf.keras.Model):
    def __init__(self, num_users, num_books, embedding_size, **kwargs):
        super(RecommenderNet, self).__init__(**kwargs)
        self.user_embedding = layers.Embedding(num_users, embedding_size, embeddings_initializer='he_normal', embeddings_regularizer=keras.regularizers.l2(1e-6))
        self.user_bias = layers.Embedding(num_users, 1)
        self.book_embedding = layers.Embedding(num_books, embedding_size, embeddings_initializer='he_normal', embeddings_regularizer=keras.regularizers.l2(1e-6))
        self.book_bias = layers.Embedding(num_books, 1)

    def call(self, inputs):
        user_vector = self.user_embedding(inputs[:,0])
        user_bias = self.user_bias(inputs[:, 0])
        book_vector = self.book_embedding(inputs[:, 1])
        book_bias = self.book_bias(inputs[:, 1])
        dot_user_book = tf.tensordot(user_vector, book_vector, 2)
        x = dot_user_book + user_bias + book_bias
        return tf.nn.sigmoid(x)

# Inisialisasi & Compile
model = RecommenderNet(num_users, num_books, 50)
model.compile(
    loss = tf.keras.losses.BinaryCrossentropy(),
    optimizer = keras.optimizers.Adam(learning_rate=0.001),
    metrics=[tf.keras.metrics.RootMeanSquaredError()]
)

# Training Model
history = model.fit(
    x = x_train, y = y_train,
    batch_size = 32, epochs = 20,
    validation_data = (x_val, y_val),
    verbose = 1
)

"""## 7. Evaluasi Collaborative Filtering (Visualisasi Metrik)
Memvisualisasikan metrik Root Mean Squared Error (RMSE) untuk melihat seberapa baik model berkonvergensi selama proses _training_.
"""

plt.plot(history.history['root_mean_squared_error'])
plt.plot(history.history['val_root_mean_squared_error'])
plt.title('Metrik Evaluasi Model (RMSE)')
plt.ylabel('root_mean_squared_error')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

"""## 8. Menguji Rekomendasi Collaborative Filtering
Mendapatkan rekomendasi buku untuk *User* tertentu berdasarkan prediksi rating dari model.
"""

# Mengambil sample user
sample_user_id = df_collab['User-ID'].sample(1).iloc[0]
buku_dibaca_oleh_user = df_collab[df_collab['User-ID'] == sample_user_id]

# Mencari buku yang belum dibaca
buku_belum_dibaca = preparation[~preparation['ISBN'].isin(buku_dibaca_oleh_user['ISBN'].values)]['ISBN']
buku_belum_dibaca = list(set(buku_belum_dibaca).intersection(set(book_to_book_encoded.keys())))

buku_belum_dibaca_encoded = [[book_to_book_encoded.get(x)] for x in buku_belum_dibaca]
user_encoder = user_to_user_encoded.get(sample_user_id)
user_book_array = np.hstack(([[user_encoder]] * len(buku_belum_dibaca_encoded), buku_belum_dibaca_encoded))

# Prediksi model
ratings = model.predict(user_book_array).flatten()

# Mendapatkan top 5 rekomendasi
top_ratings_indices = ratings.argsort()[-5:][::-1]
recommended_book_ids = [book_encoded_to_book.get(buku_belum_dibaca_encoded[x][0]) for x in top_ratings_indices]

print(f"Rekomendasi untuk User ID: {sample_user_id}\n" + "-"*35)
recommended_books = preparation[preparation['ISBN'].isin(recommended_book_ids)]
display(recommended_books[['Book-Title', 'Book-Author', 'Publisher']])